/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getPublicKey" | "publicKey" | "registerIdentity"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "IdentityRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getPublicKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publicKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIdentity",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "publicKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentity",
    data: BytesLike
  ): Result;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    publicKey: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    publicKey: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    wallet: string;
    publicKey: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPublicKey: TypedContractMethod<[_wallet: AddressLike], [string], "view">;

  publicKey: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerIdentity: TypedContractMethod<
    [_pubKey: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPublicKey"
  ): TypedContractMethod<[_wallet: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "publicKey"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerIdentity"
  ): TypedContractMethod<[_pubKey: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;

  filters: {
    "IdentityRegistered(address,bytes,uint256)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
  };
}
