/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdentityRegistry } from "./IdentityRegistry";
export * as factories from "./factories";
export { IdentityRegistry__factory } from "./factories/IdentityRegistry__factory";
